### ISSUE TITLE
API calls cached? 

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-catalog#62]
Now that we're using Cloudflare to serve all traffic via HTTPS, it seems that some API calls are being cached. When hitting the `/meta` endpoint, the last call is being returned: http://api.openaerialmap.org/meta. 

Steps to reproduce: 
1. http://api.openaerialmap.org/meta
2. http://api.openaerialmap.org/meta?limit=1
3. then check http://api.openaerialmap.org/meta

I've checked Cloudflare settings and caching mechanism are turned off. 

@scisco @kamicut @danielfdsilva This may not be problematic for the oam-browser since we're using specific API calls for views. But is this problematic for general API use?

**Comment by danielfdsilva** [comment]
Actually I had a problem on the browser because of this.
- Once you enter the app it calls http://api.openaerialmap.org/meta?limit=1 to get the latest imagery.
- The the call to get all footprints also resolves (http://api.openaerialmap.org/meta) and only returns one.
- I fixed it for now by using http://api.openaerialmap.org/meta?limit=9999 but it ain't pretty!

**Comment by kamicut** [comment]
After a couple tests, it seems that this hasn't anything to do with request headers. The `limit` parameter is stored somewhere and reused for subsequent requests.

Reproduce: changing the `/meta?limit=#` on one client will affect the `/meta` request on another client.
